# Gradle daemon JVM arguments.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Build performance.
org.gradle.caching=true
org.gradle.parallel=true

# Kotlin/Android conventions.
kotlin.code.style=official
android.useAndroidX=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
